# Generated by Django 4.2.3 on 2023-08-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_title_collection_titlle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="titlle",
            new_name="title",
        ),
    ]
