# Generated by Django 4.2.3 on 2023-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_titlle_collection_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="produckt",
            name="slug",
            field=models.SlugField(default="_"),
            preserve_default=False,
        ),
    ]
