# Generated by Django 4.2.3 on 2023-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_produckt_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produckt",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
