# Generated by Django 4.2.3 on 2023-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_address_zip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store custo_last_na_edbaf1_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store customers",
        ),
    ]
