# Generated by Django 4.2.4 on 2023-09-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_produckt_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='produckt',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='featured_produckt',
            new_name='featured_product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pleased_at',
            new_name='placed_at',
        ),
        migrations.RenameField(
            model_name='produckt',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='address',
            name='stret',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='given_name',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='unykown', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='ketmon', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='produckt',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
        ),
        migrations.AlterField(
            model_name='produckt',
            name='slug',
            field=models.SlugField(),
        ),
    ]
