# Generated by Django 4.2.4 on 2023-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at']},
        ),
        migrations.AlterModelOptions(
            name='produckt',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='produckt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
