# Generated by Django 4.2.4 on 2023-09-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_produckt_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produckt',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='store.promotion'),
        ),
    ]
