# Generated by Django 4.2.4 on 2023-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_ketmonjonlardan_aylanay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ketmonjonlardan_aylanay',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'ordering': ['object_id']},
        ),
    ]
